CREATE OR ALTER PROCEDURE SP_SYSO_ESTOQUE_EDIT_ITEM_CAR (
    ID_PK INTEGER,
    ID_PRODUTO VARCHAR(15),
    NOVA_QUANT_INTEIRA INTEGER,
    QUANT_INTEIRA INTEGER
)
returns (RESULT_FLAG INTEGER)
AS
declare variable ESTOQUE INTEGER;
BEGIN
    SELECT ESTOQUE_INTEIRO
    FROM PRODUTOS_ESTOQUES
    WHERE ID_PRODUTO = :ID_PRODUTO
    INTO :ESTOQUE;

    if (ESTOQUE >= NOVA_QUANT_INTEIRA) then
    BEGIN
        UPDATE SYSO_ESTOQUE_CARRINHO
        SET QUANT_INTEIRA = :NOVA_QUANT_INTEIRA
        WHERE ID_PRODUTO = :ID_PRODUTO AND ID_PK = :ID_PK;

        RESULT_FLAG = 1;
    END
    else
    BEGIN
        RESULT_FLAG = 0; -- Ou qualquer valor que você queira atribuir para indicar que o item não foi adicionado
    END
END;

