CREATE TABLE SYSO_ESTOQUE_LISTA_PRODUTOS (
    ID_PRODUTO         VARCHAR(13) NOT NULL,
    ID_INVENTARIO      INTEGER,
    CODIGO_BARRAS      VARCHAR(15),
    ESTOQUE_INTEIRO    DOUBLE PRECISION,
    ESTOQUE_FRACAO     DOUBLE PRECISION DEFAULT 0,
    DESCRICAO_PRODUTO  VARCHAR(40),
    DATA               DATE DEFAULT current_timestamp,
    ID_LANCAMENTO      INTEGER NOT NULL,
    DATA_FABRICACAO    DATE,
    DATA_VENCIMENTO    DATE,
    LOTE               CHAR(20),
    SITUACAO           INTEGER DEFAULT 1
);
